###________________########
##/////////\\\\\\\\\########
#//////////\\\\\\\\\\#######
#//// Xiavic Core \\\\######
#\\\\\ Plugin 2.0 ////######
#\\\\\\\\\\//////////#######
##\\\\\\\\\/////////########
###\\\\\\\\////////#########
####\\\\\\\///////##########
#####\\\\\\//////###########
######\\\\\/////############
#######\\\\////#############
#######\\_|_//##############


##############################
######## !! CONFIG !! ########
##############################
Version: 1

#Spawn | world name, X, Y, Z, Yaw, Pitch
FirstSpawn: world,100,100,100,100
Spawn: world,100,100,100,100,100

#Economy
Balance_Check: 60

#Private Warps
PWCooldown: 300
#If set to true, players will still need the permission node.
CanShare: false

#Teleport
# Time before you can send another request
TpaCooldown: 5
# Time before actually teleporting
TpaDelay: 3
# Time before the request expires
TpaTimeout: 60

#RTP
RTPCooldown: 600
RTPWorld: world
RTPDistance: 50000

#Life
HealCooldown: 600
FeedCooldown: 600
SuicideCooldown: 60

#Near Max-Distance
NearRange: 1000

#Fun
ZapDistance: 4